config/routes.rb
Rails.application.routes.draw do

  root 'games#home'
   resources :games do
     resources :comments
   end

  # root 'users#index'
  # resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/login' 'users#new'
  # This route sends requests to our naked url to the *cool* action in the *gif* controller.
# root to: 'gif#cool'

# I've created a gif controller so I have a page I can secure later.
# This is optional (as is the root to: above).
# get '/cool' => 'gif#cool'
# get '/sweet' => 'gif#sweet'

get '/index' => 'games#index'
get '/login' => 'sessions#new'
post '/login' => 'sessions#create'
get '/logout' => 'sessions#destroy'
# These routes will be for signup. The first renders a form in the browse, the second will
# receive the form and create a user in our database using the data given to us by the user.
get '/signup' => 'users#new'
post '/users' => 'users#create'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :game
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_game
  before_action :find_comment, only: [:destroy, :edit, :update, :comment_owner]
  before_action :comment_owner, only: [:destroy, :edit, :update]

  def create
    @comment = @game.comments.create(params[:comment].permit(:content))
    @comment.user_id = current_user.id
    @comment.save

    if @comment.save
      redirect_to game_path(@game)
    else
      render 'new'
    end
  end

  def destroy
    @comment.destroy
    redirect_to game_path(@game)
  end

  def edit
  end

  def update
    if @comment.update(params[:comment].permit(:content))
      redirect_to game_path(@game)
    else
      render 'edit'
    end
  end

  private

  def find_game
    @game = Game.find(params[:game_id])
  end

  def find_comment
    @comment = @game.comments.find(params[:id])
  end

  def comment_owner
    unless current_user.id == @comment.user_id
      flash[:notice] = "you shall not pass"
      redirect_to @game
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<h2>This post has <%= pluralize(@comments.count, "Reply") %> </h2>

<% @comments.each do |comment| %>

<p><b> <%= comment.user.username %></b>
posted <%= time_ago_in_words(comment.created_at) %></p>
<p> <%= comment.content  %> </p>

<% if current_user == comment.user %>
  <%= link_to "Delete comment", [comment.game, comment], method: :delete %>
  <%= link_to "Edit comment", edit_game_comment_path(comment.game, comment) %>
  <% end %>
<% end %>

<%= render 'comments/form' %>

app/views/comments/_form.html.erb
<%= form_for([@game, @game.comments.build]) do |f| %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<%= form_for([@game, @comment]) do |f| %>
<%= f.text_area :content %>
<%= f.submit %>
<% end %>