config/routes.rb
Rails.application.routes.draw do

  root 'games#home'
   resources :games do
     resources :comments
   end

  # root 'users#index'
  # resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/login' 'users#new'
  # This route sends requests to our naked url to the *cool* action in the *gif* controller.
# root to: 'gif#cool'

# I've created a gif controller so I have a page I can secure later.
# This is optional (as is the root to: above).
# get '/cool' => 'gif#cool'
# get '/sweet' => 'gif#sweet'

get '/index' => 'games#index'
get '/login' => 'sessions#new'
post '/login' => 'sessions#create'
get '/logout' => 'sessions#destroy'
# These routes will be for signup. The first renders a form in the browse, the second will
# receive the form and create a user in our database using the data given to us by the user.
get '/signup' => 'users#new'
post '/users' => 'users#create'
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :comments, dependent: :destroy
  # has_many :game_players
  # has_many :users, through: :game_players
  geocoded_by :location   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates
  validates :location, presence: true
  validates :sport, presence: true
  validates :start, presence: true
  validates :description, presence: true
  belongs_to :user



  #search method for search ability
  def self.search(search)

    p "<>"*20
    p search
    where("location iLIKE ? OR description iLIKE ? OR sport iLIKE ?",
      "%#{search}%", "%#{search}%", "%#{search}%")

  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authorize, except: [:home]
  before_action :set_game, only: [:show, :edit, :update, :destroy, :join]
  @@image_urls = { #hash with game icon, key corresponds to param of game selection
    soccer: [
      'http://cdn.mysitemyway.com/icons-watermarks/simple-black/',
      'classica/classica_soccer-ball/',
      'classica_soccer-ball_simple-black_512x512.png',].join,

    basketball: [
      'http://szeszi.net/wp-content/',
      'uploads/2015/09/Games.png'].join,

    football: ['https://upload.wikimedia.org',
      '/wikipedia/commons/a/ae/Football_Icon.svg'].join,

    kickball: ['https://fxasports.com/wp-content/uploads',
      '/2017/01/FXA-Sports-Kickball-Icon.jpg'].join,

    frisbee: ['https://d30y9cdsu7xlg0.cloudfront.net/png/171542-200.png'].join,

    volleyball: ['https://maxcdn.icons8.com/Share/icon/Sports//volleyball1600.png'].join,

    biking: ['https://d30y9cdsu7xlg0.cloudfront.net/png/29955-200.png'].join,


    baseball: ['https://cdn0.iconfinder.com/data/icons/',
      'customicondesign-office6-shadow/256/baseball.png'].join,

    yoga: ['https://image.flaticon.com/icons/png/512/84/84145.png'].join,

    default:[ #default image -- CHANGE TO LOGO
      'https://upload.wikimedia.org/',
      'wikipedia/commons/thumb/0/0c/',
      'Sport_balls.svg/2000px-Sport_balls.svg.png'].join
  }
  dimension = '25' #sets dimesnion of icon
  # string 'widthxheight' for image_tag
  @@dimensions = 2.times.map{ dimension }.join('x') #puts size in format
  @@game_icon_image = @@image_urls[:default]


  # GET /games
  # GET /games.json
def user
  @user = Game.current_user
end

  def index
    @games = Game.all
    #display games is an array that saves the game object with all info
    #saved from param and image that corresoponds to the game
    search_string = params[:search]
    if search_string.nil? || search_string.empty?
      results = Game.all.order("created_at DESC")
    elsif params[:search]
      results = Game.search(search_string).order("created_at DESC")
    end
    @display_games = results.map do |game|
      [
        game,
        @@image_urls.fetch(
        game.sport.downcase.to_sym,
        @@image_urls[:default]),
      ]
    end
    # @game_icon_image = @@game_icon_image
    @dimensions = @@dimensions
  end

  def home
  end

  # GET /games/1
  # GET /games/1.json
  def show
    # @join_users = @game.users
    @comments = Comment.where(game_id: @game).order('created_at DESC')
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)
    @game.user = current_user
    respond_to do |format|
      if @game.save
        current_user.games << @game
        # gp = GamePlayer.new #this activates the join table we need
        # gp.user_id = @current_user.id
        # gp.game_id = @game.id
        # gp.save!
        format.html { redirect_to games_path, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
      
    end

  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def join_game
      gp = GamePlayer.new
      gp.user_id = params[:user_id]
      gp.game_id = @game.id
      gp.save!
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:location, :start, :stop, :name, :sport, :description)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<div class="game-wrap">
  <div class="game-html">
    <input class="game-in"><label for="tab-1" class="tab">New Game</label>

    <%= form_with(model: game, local: true) do |form| %>
    <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>
      <ul>
        <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="group">
      <label for="user" class="label">location</label>
      <%= form.text_field :location, id: :game_location, class: "input" %>
    </div>

    <div class="group">
      <label for="user" class="label">Start</label>
      <%= form.datetime_select :start, id: :game_start, ampm: true, discard_year: true, class: "input" %>
    </div>

    <div class="group">
      <label for="user" class="label">Stop</label>
      <%= form.datetime_select :stop, id: :game_stop, ampm: true, discard_year: true,  class: "input" %>
    </div>

    <div class="group">
      <div >
        <label for="user" class="label">Sport</label>

        <%= form.select(:sport,options_for_select([['select one', nil],['SOCCER','SOCCER'],
        ['BASKETBALL','BASKETBALL'],['FOOTBALL','FOOTBALL'],['KICKBALL','KICKBALL'],
        ['FRISBEE','FRISBEE'],['VOLLEYBALL','VOLLEYBALL'],
        ['BASEBALL/SOFTBALL','BASEBALL/SOFTBALL'],['BIKING','BIKING'],['YOGA','YOGA'],['OTHER','OTHER']]),{},{id: "options"}) %>

      </div>
    </div>

    <div class="disc">
      <div class="label">
        <%= form.label :description %>
      </div>
      <%= form.text_area :description, id: :game_description , placeholder: "Location Details, Attire Details so that other players can find you,Age Range, Skill Level"%>

    </div>


    <div class="group">

      <%= form.submit class: "button" %>
    

    </div>

    <% end %>

  </div>
</div>

app/views/games/_map.html.erb
<div id="map"></div>

app/views/games/edit.html.erb
<h1>Editing Game</h1>


<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCYsFrnvKIEmREiU0uHWk0SI-KnU7J1cbc&libraries=places&callback=initAutocomplete"> </script>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/edit.js.erb
$('.modal-body').html("<%= j render 'form', game: @game%>")
// target the modal body in out index , then render the form that was origially in
//  our edit page and use the  @task to display what we will edit....basically
//  put the entire edit page into a little pop up box,and all

// edditing is done in the box.
$('.modal').modal();

app/views/games/home.html.erb
<div class = "top">

  <div class="logo-search">
    <img src ="assets/playerlogo.png"></img>

    <div class="search-box">
      <%= form_tag(games_path, :method => "get") do %>
      <div class = "form-group">
        <%= search_field_tag :search, params[:search], placeholder: "Search Sport" , class:"form-control"%>
      </div>
      <div class = "form-group">
        <%= search_field_tag :search, params[:search], placeholder: "Search Zipcode, Location" , class:"form-control"%>
      </div>
      <%= submit_tag 'Search', class: "btn btn-block btn-sm btn-primary " %>
      <% end %>
    </div>
  </div>
</div>

app/views/games/index.html.erb
<div class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Game</h4>
      </div>
      <div class="modal-body">
        <p>One fine body&hellip;</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<body class="games-display">
  <div class="background-display">
    <div class="container-map-box">
      <div class="container-map">
      <div id="map"></div>

      </div>
    </div>

    <div class="container-games">


      <button id="new" type="button" class="btn btn-outline-success"><%= link_to 'New Game', new_game_path %></button>

      <%= hidden_field_tag 'games_lat_and_lng', @games.map {|g| {:lat => g.latitude, :lng => g.longitude, :description => g.description}}.to_json %>
      <table>
        </thead>

        <tbody>
          <!-- will display game info along with corresoponding image -->
          <div><% @display_games.each do |game, icon_url| %></div>


            <div><tr>
              <td><%= image_tag icon_url, size: @dimensions %></td>
              <td id="location"><%= game.location %></td>
              <td id="location"><%= game.start.strftime("%a, %B %d, %I:%M%P") %> </td>
              <td id="location"><%= game.stop.strftime("%a, %B %d, %I:%M%P") %></td>
              <td id="location"><%= game.sport %></td>



              <td id="show"><button type="button" class="btn btn-outline-success button-size-small"><%= link_to 'Show', game, remote: true%></button></td>





            </tr>
          <% end %>
          </div>



        </tbody>

      </table>
      <br>
    </div>
  </div>

app/views/games/new.html.erb
<div class = "newgame">

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>
</div>

app/views/games/show.html.erb
<%= hidden_field_tag 'games_lat_and_lng', [{:lat => @game.latitude, :lng => @game.longitude, :description => @game.description}].to_json %>

<%= render 'map' %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @game.location %>
</p>

<p>
  <strong>Start:</strong>
  <%= @game.start.strftime("%a, %B %d, %I:%M%P") %>
</p>

<p>
  <strong>Stop:</strong>
  <%= @game.stop.strftime("%a, %B %d, %I:%M%P") %>
</p>

<p>
  <strong>Sport:</strong>
  <%= @game.sport %>
</p>

<p>
  <strong>Description:</strong>
  <%= @game.description %>
</p>

<%= render 'comments/comment' %>
<%= link_to 'Edit', edit_game_path(@game) %>
<%= link_to 'Back', games_path %>

app/views/games/show.js.erb
$('.modal-body').html("<p><strong>Location:</strong><%=@game.location%></p>" +
"<p><strong>Start: </strong><%= @game.start.strftime("%a, %B %d, %I:%M%P") %></p>"+
"<p><strong>Stop:</strong><%= @game.stop.strftime("%a, %B %d, %I:%M%P") %></p>" +
"<p><strong>Sport: </strong><%=@game.sport%></p>" +
"<p><strong>Description: </strong><%= @game.description %></p> ")

$('.modal-body').append("<%= escape_javascript render(:partial => 'comments/comment') %>");


// $('.modal-body form').find('.actions').find('input[type=submit]').remove();

$('.modal').modal();